export default {
  extends: ["stylelint-config-standard"],
  rules: {
    "custom-property-empty-line-before": null,
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "color-function-alias-notation": null,
    "color-function-notation": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-empty-line-before": null,
    "declaration-block-single-line-max-declarations": null,
    "import-notation": null,
    "media-feature-range-notation": null,
    "no-descending-specificity": null,
    "property-no-deprecated": null,
    "rule-empty-line-before": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-max-id": 0,
    "selector-max-specificity": "0,4,1",
    "selector-not-notation": null,
    "selector-pseudo-element-colon-notation": null,
  },
};
